# Generated by Django 4.0 on 2021-12-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField(default=False)),
                ('has_posted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscipleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('date', models.DateField(default='2021-01-01')),
                ('is_read', models.BooleanField(default=False)),
                ('disciple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='disciplenowapi.disciple')),
                ('lead_disciple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='disciplenowapi.disciple')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('date', models.DateField(default='2021-01-01')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.disciplegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hear', models.CharField(max_length=500)),
                ('engage', models.CharField(max_length=500)),
                ('apply', models.CharField(max_length=500)),
                ('respond', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=20)),
                ('date', models.DateField(default='2021-01-01')),
                ('disciple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.disciple')),
            ],
        ),
        migrations.CreateModel(
            name='DiscipleToMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.disciple')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='DiscipleToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.disciple')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.disciplegroup')),
            ],
        ),
        migrations.AddField(
            model_name='disciplegroup',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.grouptype'),
        ),
        migrations.AddField(
            model_name='disciplegroup',
            name='lead_disciple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplenowapi.disciple'),
        ),
        migrations.AddField(
            model_name='disciple',
            name='groups',
            field=models.ManyToManyField(related_name='group_disciples', through='disciplenowapi.DiscipleToGroup', to='disciplenowapi.DiscipleGroup'),
        ),
        migrations.AddField(
            model_name='disciple',
            name='meetings',
            field=models.ManyToManyField(related_name='attending_disciples', through='disciplenowapi.DiscipleToMeeting', to='disciplenowapi.Meeting'),
        ),
        migrations.AddField(
            model_name='disciple',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
